import { randomUUID } from 'node:crypto';
import type { JobDatabase } from './db.js';
import { adjacentRoles, buildTransitionAssessment, canonicalTransitionRole, type TransitionAssessment } from '../domain/careerTransition.js';
import { normalizeText } from '../domain/ontology.js';

type Profile={desired_roles:string};type Experience={title:string;normalized_title:string};type Fact={normalized_value:string;status:string};type Credential={normalized_name:string};type UserSkill={canonical_name:string;status:string};
type Job={id:string;title:string|null;normalized_title:string|null;salary_min:number|null;salary_max:number|null;salary_period:string|null;gross_net:string|null};type Req={job_id:string;canonical_requirement:string;importance:string};type Local={role_name:string;normalized_role:string;role_aliases:string;salary_min:number|null;salary_max:number|null;source_name:string};
const strings=(raw:string):string[]=>{try{const v=JSON.parse(raw) as unknown;return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string'):[];}catch{return[];}};
function roleMatch(target:string,title:string|null):boolean{const a=normalizeText(target),b=normalizeText(title??'');return b===a||b.includes(a)||a.includes(b);}
function localRoleMatch(target:string,row:Local):boolean{const n=normalizeText(target);return row.normalized_role===n||strings(row.role_aliases).some(a=>normalizeText(a)===n);}
export interface CareerTransitionReport{sourceRole:string;paths:TransitionAssessment[];message:string;}
export class CareerTransitionService{
 constructor(private readonly database:JobDatabase){} private get db(){return this.database.db;}
 build(userId:string):CareerTransitionReport{
  const profile=this.db.prepare('SELECT desired_roles FROM career_profiles WHERE user_id=?').get(userId) as Profile|undefined;const desired=profile?strings(profile.desired_roles):[];
  const exp=this.db.prepare('SELECT title,normalized_title FROM career_experiences WHERE user_id=? ORDER BY current DESC,start_date DESC LIMIT 1').get(userId) as Experience|undefined;
  const sourceRaw=desired[0]||exp?.normalized_title||exp?.title||'';const sourceRole=canonicalTransitionRole(sourceRaw);if(!sourceRole)return{sourceRole:'',paths:[],message:'Najpierw ustaw rolę docelową lub doświadczenie w profilu.'};
  const targets=adjacentRoles(sourceRole);if(!targets.length)return{sourceRole,paths:[],message:`Dla roli „${sourceRole}” kuratorowany graf V2 nie ma jeszcze bezpiecznie zdefiniowanego sąsiedztwa.`};
  const facts=this.db.prepare('SELECT normalized_value,status FROM career_facts WHERE user_id=?').all(userId) as unknown as Fact[];const credentials=this.db.prepare("SELECT normalized_name FROM credentials WHERE user_id=? AND status='CONFIRMED'").all(userId) as unknown as Credential[];const skills=this.db.prepare('SELECT s.canonical_name,us.status FROM user_skills us JOIN skills s ON s.id=us.skill_id WHERE us.user_id=?').all(userId) as unknown as UserSkill[];
  const confirmed=new Set([...facts.filter(f=>f.status==='CONFIRMED').map(f=>normalizeText(f.normalized_value)),...credentials.map(c=>normalizeText(c.normalized_name)),...skills.filter(s=>s.status==='CONFIRMED').map(s=>normalizeText(s.canonical_name))]);
  const jobs=this.db.prepare('SELECT id,title,normalized_title,salary_min,salary_max,salary_period,gross_net FROM jobs WHERE user_id=?').all(userId) as unknown as Job[];const reqs=this.db.prepare('SELECT r.job_id,r.canonical_requirement,r.importance FROM job_requirements r JOIN jobs j ON j.id=r.job_id WHERE j.user_id=?').all(userId) as unknown as Req[];const local=this.db.prepare('SELECT role_name,normalized_role,role_aliases,salary_min,salary_max,source_name FROM local_labour_snapshots').all() as unknown as Local[];
  const paths=targets.map(target=>{const targetJobs=jobs.filter(j=>roleMatch(target,j.normalized_title??j.title));const ids=new Set(targetJobs.map(j=>j.id));const targetReqs=reqs.filter(r=>ids.has(r.job_id)&&r.importance==='MUST_HAVE');const requirements=[...new Set(targetReqs.map(r=>r.canonical_requirement))];const transferable=requirements.filter(r=>confirmed.has(normalizeText(r)));const missing=requirements.filter(r=>!confirmed.has(normalizeText(r)));const localRows=local.filter(r=>localRoleMatch(target,r));const salaryValues=[...targetJobs.filter(j=>j.salary_period==='MONTH').flatMap(j=>[j.salary_min,j.salary_max]),...localRows.flatMap(r=>[r.salary_min,r.salary_max])].filter((v):v is number=>v!==null&&Number.isFinite(v));return buildTransitionAssessment({sourceRole,targetRole:target,savedJobs:targetJobs.length,localMentions:localRows.length,localSourceCount:new Set(localRows.map(r=>r.source_name)).size,salaryMin:salaryValues.length?Math.min(...salaryValues):null,salaryMax:salaryValues.length?Math.max(...salaryValues):null,transferableSkills:transferable,missingSkills:missing,confirmedSkillCount:transferable.length,targetRequirementCount:requirements.length,suggestedLearning:missing.slice(0,3)});});
  return{sourceRole,paths,message:`Pokazujemy sąsiednie role z kuratorowanego grafu i konfrontujemy je wyłącznie z Twoimi zapisanymi ofertami, Career Truth i dostępnymi danymi lokalnymi.`};
 }
 recordExploration(userId:string,path:TransitionAssessment):string{const id=randomUUID();this.db.prepare('INSERT INTO career_transition_explorations(id,user_id,source_role,target_role,confidence,created_at) VALUES(?,?,?,?,?,?)').run(id,userId,path.sourceRole,path.targetRole,path.confidence,new Date().toISOString());return id;}
}
