INSERT OR IGNORE INTO job_source_registry(key,label,kind,enabled,terms_metadata,health_status,health_message,last_checked_at,created_at,updated_at)
VALUES
('pracuj','Pracuj.pl','PARTNERSHIP',0,'{"searchMode":"OUTBOUND_SEARCH","ingestionStatus":"PARTNER_REQUIRED","checkedAt":"2026-09-13","notes":"Bezpieczne wyszukiwanie wychodzące. Automatyczny import wymaga potwierdzonego, dozwolonego kanału danych."}','UNKNOWN','Automatyczny import nie jest skonfigurowany.',NULL,datetime('now'),datetime('now')),
('linkedin','LinkedIn Jobs','PARTNERSHIP',0,'{"searchMode":"OUTBOUND_SEARCH","ingestionStatus":"PARTNER_REQUIRED","checkedAt":"2026-09-13","notes":"Jobs API jest ograniczone do zatwierdzonych integracji partnerskich."}','UNKNOWN','Automatyczny import nie jest skonfigurowany.',NULL,datetime('now'),datetime('now')),
('olx','OLX Praca','PARTNERSHIP',0,'{"searchMode":"OUTBOUND_SEARCH","ingestionStatus":"PARTNER_REQUIRED","checkedAt":"2026-09-13","notes":"OLX API wymaga zatwierdzenia aplikacji i nie udostępnia pobierania ogłoszeń innych użytkowników przez publiczne API."}','UNKNOWN','Automatyczny import nie jest skonfigurowany.',NULL,datetime('now'),datetime('now')),
('indeed','Indeed','PARTNERSHIP',0,'{"searchMode":"OUTBOUND_SEARCH","ingestionStatus":"PARTNER_REQUIRED","checkedAt":"2026-09-13","notes":"Automatyczna integracja wymaga dostępu partnerskiego Indeed."}','UNKNOWN','Automatyczny import nie jest skonfigurowany.',NULL,datetime('now'),datetime('now')),
('rocketjobs','RocketJobs','PARTNERSHIP',0,'{"searchMode":"OUTBOUND_SEARCH","ingestionStatus":"PARTNER_REQUIRED","checkedAt":"2026-09-13","notes":"Automatyczny import pozostaje wyłączony do czasu potwierdzenia feedu/API lub partnerstwa."}','UNKNOWN','Automatyczny import nie jest skonfigurowany.',NULL,datetime('now'),datetime('now')),
('justjoinit','Just Join IT','PARTNERSHIP',0,'{"searchMode":"OUTBOUND_SEARCH","ingestionStatus":"PARTNER_REQUIRED","checkedAt":"2026-09-13","notes":"Automatyczny import pozostaje wyłączony do czasu potwierdzenia feedu/API lub partnerstwa."}','UNKNOWN','Automatyczny import nie jest skonfigurowany.',NULL,datetime('now'),datetime('now')),
('employer_careers','Strony karier pracodawców','PERMITTED_CAREER_PAGE',0,'{"searchMode":"DIRECT_CAREER_PAGES","ingestionStatus":"PERMITTED_SOURCE_REQUIRED","checkedAt":"2026-09-13","notes":"Automatyczne pobieranie wyłącznie z jawnie dozwolonych i skonfigurowanych stron karier."}','UNKNOWN','Brak skonfigurowanej allowlisty stron karier.',NULL,datetime('now'),datetime('now'));
