import { test, expect, type Page } from '@playwright/test';
import { AxeBuilder } from '@axe-core/playwright';

async function auth(page:Page){await page.route('**/api/me',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({user:{id:'v15-user',email:'v15@example.pl',name:'Tester',role:'USER',locale:'pl-PL',timezone:'Europe/Warsaw'},profile:{desiredRoles:['magazynier'],location:'Gdynia',commuteKm:25,remotePreferences:['ONSITE'],salaryMin:5500,contractPreferences:['UOP'],shiftPreferences:{nights:null,weekends:null},availability:'od zaraz'},subscription:{plan:'TRIAL',status:'TRIALING'}})}));await page.route('**/api/career-truth',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({facts:[],experiences:[],education:[]})}));}

test('Skill ROI and just-in-time learning expose evidence, uncertainty and bounded plans',async({page})=>{await auth(page);await page.route('**/api/features',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({features:{skill_roi:true,just_in_time_learning:true,effective_wage:false,local_labour:false,bottleneck:false,job_feed:false,today:false,notifications:false,interview_pack:false,career_transition:false,outcome_inbox:false,strategy_engine:false}})}));
const report={candidates:[{skill:'UDT',normalizedSkill:'udt',ontologyType:'CREDENTIAL',requirementCount:6,mustHaveCount:4,savedJobSample:8,potentiallyUnlockedJobs:2,localMentions:1,localSourceCount:1,salaryDifference:null,salarySample:0,possession:'NOT_CONFIRMED',assumption:null,confidence:'WCZESNY_SYGNAL',opportunityScore:20,evidence:['W zapisanej próbce 8 ofert ta kompetencja pojawia się w 6 ofertach.','Oferty, w których jest jedynym niepotwierdzonym wymaganiem MUST_HAVE: 2.'],uncertainty:['Brak potwierdzenia tej kompetencji w Career Truth nie oznacza, że jej nie masz.','Nie ma wystarczającej porównywalnej próbki płac; nie zgadujemy premii wynagrodzenia.'],nextStep:'Uzupełnij własny koszt i czas nauki.'}],savedJobSample:8,confidence:'WCZESNY_SYGNAL',message:'Ranking opiera się na 8 zapisanych ofertach. Nie jest obietnicą zatrudnienia ani zwrotu finansowego.'};
await page.route('**/api/skill-roi',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({report})}));await page.route('**/api/skill-roi/assumptions/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({report})}));const target={kind:'MISSING_SKILL',key:'udt',label:'UDT',context:'Wymaganie powtarza się w zapisanych ofertach.',evidence:['UDT jest wymaganiem zapisanych ofert.'],unknowns:['Nie znamy aktualnych zasad certyfikacji.']};await page.route('**/api/learning/targets',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({targets:[target]})}));await page.route('**/api/learning/plan',r=>r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({plan:{target,budgetMinutes:15,tasks:[{minutes:5,title:'Cel',instruction:'Sprawdź wymaganie.'},{minutes:7,title:'Przykład',instruction:'Przygotuj prawdziwy przykład.'},{minutes:3,title:'Sprawdzenie',instruction:'Zweryfikuj jedną rzecz.'}],boundaries:['Plan nie potwierdza certyfikacji.']}})}));
await page.goto('/');await expect(page.locator('#appView')).not.toHaveClass(/hidden/);await page.locator('[data-view="skill-roi"]:visible').first().click();await expect(page.getByRole('heading',{name:'Czego najbardziej opłaca Ci się teraz nauczyć?'})).toBeVisible();await expect(page.locator('#skillRoiResult')).toContainText('nie oznacza, że jej nie masz');await expect(page.locator('#skillRoiResult')).toContainText('potencjalnie odblokowanych ofert');let axe=await new AxeBuilder({page}).include('[data-screen="skill-roi"]').analyze();expect(axe.violations).toEqual([]);
await page.locator('[data-view="learning"]:visible').first().click();await expect(page.getByRole('heading',{name:'Szybka nauka pod konkretny cel'})).toBeVisible();await page.getByRole('button',{name:'Ułóż plan'}).click();await expect(page.locator('#learningPlan')).toContainText('Plan nie potwierdza certyfikacji');axe=await new AxeBuilder({page}).include('[data-screen="learning"]').analyze();expect(axe.violations).toEqual([]);});
