import { test, expect, type Page } from '@playwright/test';
import { AxeBuilder } from '@axe-core/playwright';

async function mockAuthenticatedUser(page:Page):Promise<void>{await page.route('**/api/me',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({user:{id:'strategy-ui',email:'strategy-ui@example.pl',name:'Tester Strategii',role:'USER',locale:'pl-PL',timezone:'Europe/Warsaw'},profile:{desiredRoles:['magazynier'],location:'Gdynia',commuteKm:25,remotePreferences:[],salaryMin:null,contractPreferences:[],shiftPreferences:{nights:null,weekends:null},availability:null},subscription:{plan:'TRIAL',status:'TRIALING'}})}));await page.route('**/api/career-truth',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({facts:[],experiences:[],education:[]})}));}

test('Strategy Engine presents cautious user-only experiments and records an explicit decision',async({page})=>{
 await mockAuthenticatedUser(page);await page.route('**/api/features',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({features:{strategy_engine:true,outcome_inbox:false,career_transition:false,skill_roi:false,just_in_time_learning:false,effective_wage:false,local_labour:false,bottleneck:false,job_feed:false,today:false,notifications:false,interview_pack:false}})}));
 const report={activated:true,confidence:'PRAWDOPODOBNY_WNIOSEK',minimumApplications:10,message:'Rekomendacje są hipotezami do małych, mierzalnych eksperymentów. Nie są pewnymi decyzjami zawodowymi.',dataSummary:{applications:24,responses:9,interviews:5,offers:2},recommendations:[{key:'ROLE_FOCUS:magazynier:produkcja',kind:'ROLE_FOCUS',headline:'Przetestuj większy udział roli „magazynier”.',reason:'W Twojej własnej historii progresja była wyższa dla tej roli.',action:'Przez kolejnych 5 aplikacji zwiększ udział tej roli i porównaj wynik.',confidence:'PRAWDOPODOBNY_WNIOSEK',sampleSize:16,scope:'EXPERIMENT',evidence:['Porównanie obejmuje wyłącznie Twoje zapisane aplikacje.'],caveats:['To korelacja w Twojej historii, nie dowód przyczynowy.']}]};
 await page.route('**/api/strategy',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({report})}));let decided=false;await page.route('**/api/strategy/recommendations/**/decision',route=>{decided=true;return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({recommendation:report.recommendations[0],decision:'ACCEPTED'})});});
 await page.goto('/');await expect(page.locator('#appView')).not.toHaveClass(/hidden/);await page.locator('[data-view="strategy"]:visible').first().click();await expect(page.getByRole('heading',{name:'Co warto przetestować dalej?'})).toBeVisible();const screen=page.locator('[data-screen="strategy"]');await expect(screen).toContainText('hipotezy do małych eksperymentów');await expect(screen).toContainText('nie wyciąga mocnych wniosków z małych prób');await expect(screen).toContainText('PRAWDOPODOBNY WNIOSEK');await expect(screen).toContainText('To korelacja');await page.getByRole('button',{name:'Przyjmuję ten eksperyment'}).click();await expect(page.locator('#strategyMessage')).toContainText('Eksperyment zapisany');expect(decided).toBe(true);const axe=await new AxeBuilder({page}).include('[data-screen="strategy"]').analyze();expect(axe.violations).toEqual([]);
});
