type Json = Record<string, unknown>;
type Me = { user:{id:string;email:string;name:string;role:string}; profile:{desiredRoles:string[];location:string|null;commuteKm:number|null;remotePreferences:string[];salaryMin:number|null;salaryMode?:'EXCLUDE_LOWER'|'DISCLOSED_ONLY';contractPreferences:string[];shiftPreferences:{nights:boolean|null;weekends:boolean|null};availability:string|null}; subscription:Json|null };
type Consent = {type:string;granted:boolean;version:string;createdAt:string};
const $=<T extends Element=HTMLElement>(s:string)=>document.querySelector(s) as T;
const $$=<T extends Element=HTMLElement>(s:string)=>[...document.querySelectorAll(s)] as T[];
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const value=(f:FormData,k:string)=>String(f.get(k)??'').trim();
const values=(f:FormData,k:string)=>f.getAll(k).map(String).filter(Boolean);
let me:Me|null=null; let currentJob=''; let currentDecision='';

async function api<T=Json>(path:string,init:RequestInit={}):Promise<T>{
  const r=await fetch(path,{...init,headers:{...(init.body?{'content-type':'application/json'}:{}),...(init.headers??{})}});
  const data=await r.json().catch(()=>({})) as T&{error?:{message?:string}};
  if(!r.ok) throw new Error(data.error?.message??`HTTP ${r.status}`); return data;
}
const body=(x:unknown)=>JSON.stringify(x);
function msg(sel:string,text:string,ok=false){const e=$(sel);e.textContent=text;e.className=`message ${ok?'success':'error'}`;}
function toast(text:string){const e=$('#toast');e.textContent=text;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2600);}
function showScreen(name:string){$$('[data-screen]').forEach(e=>e.classList.toggle('hidden',e.getAttribute('data-screen')!==name));$$('[data-view]').forEach(e=>e.classList.toggle('active',e.getAttribute('data-view')===name)); if(name==='applications')void loadApplications(); if(name==='privacy')void loadPrivacy(); if(name==='admin')void loadAdmin();}
function authMode(mode:string){$$('[data-auth-tab]').forEach(e=>e.classList.toggle('active',e.getAttribute('data-auth-tab')===mode));$('#loginForm').classList.toggle('hidden',mode!=='login');$('#registerForm').classList.toggle('hidden',mode!=='register');}
function setLoggedIn(logged:boolean){$('#authView').classList.toggle('hidden',logged);$('#appView').classList.toggle('hidden',!logged);$('#logoutButton').classList.toggle('hidden',!logged);}

async function loadMe(){
  try{me=await api<Me>('/api/me');setLoggedIn(true);$('#welcomeTitle').textContent=`Dzień dobry, ${me.user.name}`;$('#userSummary').innerHTML=`<strong>${esc(me.user.name)}</strong><br><span class="hint">${esc(me.user.email)}</span>`;$('#adminLink').classList.toggle('hidden',me.user.role!=='ADMIN');fillProfile();fillWizardProfile();await loadCareerTruth();$('#startStatus').innerHTML=`<strong>Plan:</strong> ${esc((me.subscription?.plan as string)??'—')} · <strong>Status:</strong> ${esc((me.subscription?.status as string)??'—')}`;showScreen(location.hash.slice(1)||'start');}
  catch{me=null;setLoggedIn(false);}
}
function syncRolesChips(inputName:string,containerId:string){const input=$(`input[name="${inputName}"]`) as HTMLInputElement|null;const container=$(containerId);if(!input||!container)return;const roles=input.value.split(',').map(s=>s.trim()).filter(Boolean);if(roles.length===0){container.innerHTML='';container.classList.add('hidden');}else{container.classList.remove('hidden');container.innerHTML=roles.map((role,idx)=>`<span class="role-chip"><span>${esc(role)}</span><button type="button" class="role-chip-remove" data-input-name="${inputName}" data-role-index="${idx}" aria-label="Usuń rolę: ${esc(role)}" title="Usuń">&times;</button></span>`).join('');}}
function fillProfile(){if(!me)return;const f=$<HTMLFormElement>('#profileForm');const p=me.profile;(f.elements.namedItem('desiredRoles') as HTMLInputElement).value=p.desiredRoles.join(', ');syncRolesChips('desiredRoles','#profileRolesChips');(f.elements.namedItem('location') as HTMLInputElement).value=p.location??'';(f.elements.namedItem('commuteKm') as HTMLInputElement).value=p.commuteKm?.toString()??'';(f.elements.namedItem('salaryMin') as HTMLInputElement).value=p.salaryMin?.toString()??'';(f.elements.namedItem('availability') as HTMLInputElement).value=p.availability??'';const mode=p.salaryMode??'EXCLUDE_LOWER';$$<HTMLInputElement>('#profileForm [name=salaryMode]').forEach(x=>x.checked=x.value===mode);$$<HTMLInputElement>('[name=remote]').forEach(x=>x.checked=p.remotePreferences.includes(x.value));$$<HTMLInputElement>('[name=contract]').forEach(x=>x.checked=p.contractPreferences.includes(x.value));(f.elements.namedItem('allowNights') as HTMLInputElement).checked=p.shiftPreferences.nights===true;(f.elements.namedItem('allowWeekends') as HTMLInputElement).checked=p.shiftPreferences.weekends===true;}
function fillWizardProfile(){if(!me)return;const f=$<HTMLFormElement>('#wizardFormStep1');if(!f)return;const p=me.profile;const set=(n:string,v:string)=>{const el=f.elements.namedItem(n) as HTMLInputElement|null;if(el)el.value=v;};set('wizardDesiredRoles',p.desiredRoles.join(', '));syncRolesChips('wizardDesiredRoles','#wizardRolesChips');set('wizardLocation',p.location??'');set('wizardCommuteKm',p.commuteKm?.toString()??'');set('wizardSalaryMin',p.salaryMin?.toString()??'');const mode=p.salaryMode??'EXCLUDE_LOWER';$$<HTMLInputElement>('#wizardFormStep1 [name=wizardSalaryMode]').forEach(x=>x.checked=x.value===mode);}
function setWizardStep(step:number){$$<HTMLButtonElement>('[data-wizard-tab]').forEach(tab=>{const num=Number(tab.dataset.wizardTab);const active=num===step;const completed=num<step;tab.classList.toggle('active',active);tab.classList.toggle('completed',completed);tab.setAttribute('aria-selected',active?'true':'false');});const pct=step===1?33:(step===2?66:100);const bar=$('.wizard-progress-bar');if(bar)bar.setAttribute('aria-valuenow',String(pct));const fill=$('#wizardProgressFill');if(fill)fill.style.width=`${pct}%`;$('#wizardStep1').classList.toggle('hidden',step!==1);$('#wizardStep2').classList.toggle('hidden',step!==2);$('#wizardStep3').classList.toggle('hidden',step!==3);}

async function loadCareerTruth(){
  const d=await api<{facts:Array<Json>;experiences:Array<Json>}>('/api/career-truth');$('#factsCount').textContent=String(d.facts.length);
  $('#factsList').innerHTML=d.facts.length?d.facts.map(f=>{const actions:string[]=[];if(f.status==='INFERRED')actions.push(`<button class="mini-button good" data-fact="${esc(f.id)}" data-status="CONFIRMED">Potwierdź</button>`);if(f.status!=='NOT_POSSESSED')actions.push(`<button class="mini-button bad" data-fact="${esc(f.id)}" data-status="NOT_POSSESSED">To nieprawda</button>`);if(f.source==='USER')actions.push(`<button class="mini-button bad" data-delete-fact="${esc(f.id)}" aria-label="Usuń fakt ${esc(f.value)}">Usuń</button>`);return `<div class="fact-item"><strong>${esc(f.value)}</strong><div class="fact-meta"><span>${esc(f.type)}</span><span>${esc(f.status)}</span><span>źródło: ${esc(f.source)}</span></div>${actions.length?`<div class="fact-actions">${actions.join('')}</div>`:''}</div>`;}).join(''):'<p class="hint">Brak faktów. Dodaj je ręcznie albo wczytaj CV.</p>';
  $('#experiencesList').innerHTML=d.experiences.map(x=>{const dates=[x.startDate,x.current?'obecnie':x.endDate].filter(Boolean).map(esc).join(' – ');return `<div class="fact-item"><strong>${esc(x.title)}</strong> — ${esc(x.employer)}${dates?`<div class="hint">${dates}</div>`:''}<div class="fact-actions"><button class="mini-button bad" data-delete-experience="${esc(x.id)}" aria-label="Usuń doświadczenie ${esc(x.title)} w ${esc(x.employer)}">Usuń</button></div></div>`;}).join('')||'<p class="hint">Brak doświadczenia.</p>';
  const count=d.facts.length;const preview=$('#wizardFactsPreview');const summary=$('#wizardFactsSummary');if(preview&&summary){if(count>0){const confirmed=d.facts.filter(f=>f.status==='CONFIRMED').length;summary.textContent=`${count} ${count===1?'fakt':count<5?'fakty':'faktów'} (w tym ${confirmed} potwierdzonych)`;preview.classList.remove('hidden');}else{preview.classList.add('hidden');}}
}

async function loadApplications(){
  const d=await api<{applications:Array<Json>}>('/api/applications');
  $('#applicationsList').innerHTML=d.applications.map(a=>`<article class="card application-card"><div class="application-head"><div><strong>${esc(a.title||'Oferta')}</strong><div class="hint">${esc(a.company||'')}</div></div><span class="badge">${esc(a.status)}</span></div><div class="application-actions"><select data-app-status="${esc(a.id)}"><option>SAVED</option><option>APPLIED</option><option>CONTACTED</option><option>INTERVIEW</option><option>OFFER</option><option>CLOSED</option></select><select data-outcome="${esc(a.id)}"><option value="">Zapisz wynik…</option><option>NO_RESPONSE</option><option>CONTACTED</option><option>INTERVIEW</option><option>REJECTED</option><option>OFFER</option><option>WAITING</option></select></div></article>`).join('')||'<div class="card"><p>Nie masz jeszcze zapisanych aplikacji.</p></div>';
  $$<HTMLSelectElement>('[data-app-status]').forEach(s=>{const app=d.applications.find(a=>a.id===s.dataset.appStatus);if(app)s.value=String(app.status);});
}
async function loadBilling(){const d=await api<{subscription:Json|null;checkoutConfigured:boolean}>('/api/billing');$('#billingStatus').innerHTML=`<p><strong>${esc(d.subscription?.plan??'FREE')}</strong> · ${esc(d.subscription?.status??'—')}</p><p class="hint">Płatności online: ${d.checkoutConfigured?'skonfigurowane':'jeszcze nieskonfigurowane'}.</p>`;}
async function loadConsents(){const d=await api<{legalVersion:string;consents:Consent[]}>('/api/consents');const byType=new Map(d.consents.map(c=>[c.type,c]));const terms=byType.get('TERMS'),privacy=byType.get('PRIVACY'),analytics=byType.get('ANALYTICS');$('#consentStatus').innerHTML=`<div><strong>Warunki:</strong> ${terms?.granted?'zaakceptowane':'brak'} <span class="hint">${esc(terms?.version??d.legalVersion)}</span></div><div><strong>Prywatność:</strong> ${privacy?.granted?'potwierdzona':'brak'} <span class="hint">${esc(privacy?.version??d.legalVersion)}</span></div>`;$<HTMLInputElement>('#analyticsConsent').checked=analytics?.granted===true;}
async function loadPrivacy(){await Promise.all([loadBilling(),loadConsents()]);}
async function loadAdmin(){try{$('#adminDiagnostics').textContent=JSON.stringify(await api('/api/admin/diagnostics'),null,2);}catch(e){$('#adminDiagnostics').textContent=(e as Error).message;}}

function renderDecision(d:{decisionId:string;decision:Json}){currentDecision=d.decisionId;const x=d.decision as {label?:string;recommendation?:string;explanation?:{why?:string[];unknown?:string[];missing?:string[];hardConstraints?:string[];conclusion?:string}};const list=(title:string,a:string[]|undefined)=>`<div class="decision-block"><h4>${title}</h4>${a?.length?`<ul>${a.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:'<p class="hint">Brak.</p>'}</div>`;$('#decisionArea').innerHTML=`<article class="card decision-card"><span class="decision-label">${esc(x.label??x.recommendation)}</span><h3>${esc(x.explanation?.conclusion)}</h3><div class="decision-columns">${list('Dlaczego',x.explanation?.why)}${list('Nie wiemy',x.explanation?.unknown)}${list('Brakuje / ryzyka',[...(x.explanation?.missing??[]),...(x.explanation?.hardConstraints??[])])}</div><div class="fact-actions"><button id="prepareButton" class="button button-primary">Przygotuj aplikację</button><button data-override="APPLY" class="button button-secondary">Mimo wszystko aplikuję</button><button data-override="SKIP" class="button button-ghost">Odpuszczam</button></div><div id="packageArea"></div></article>`;}

$$('[data-auth-tab]').forEach(e=>e.addEventListener('click',()=>authMode(e.getAttribute('data-auth-tab')||'login')));$$('[data-view]').forEach(e=>e.addEventListener('click',()=>{const v=e.getAttribute('data-view')||'start';location.hash=v;showScreen(v);}));
$('#loginForm').addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget as HTMLFormElement);try{await api('/api/auth/login',{method:'POST',body:body({email:value(f,'email'),password:value(f,'password')})});await loadMe();}catch(e){msg('#authMessage',(e as Error).message);}});
$('#registerForm').addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget as HTMLFormElement);try{await api('/api/auth/register',{method:'POST',body:body({name:value(f,'name'),email:value(f,'email'),password:value(f,'password'),acceptTerms:f.has('acceptTerms'),acceptPrivacy:f.has('acceptPrivacy'),analyticsConsent:f.has('analyticsConsent')})});await loadMe();}catch(e){msg('#authMessage',(e as Error).message);}});
$('#logoutButton').addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'});location.hash='';setLoggedIn(false);});
$('#profileForm').addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget as HTMLFormElement);const n=(k:string)=>value(f,k)?Number(value(f,k)):null;await api('/api/profile',{method:'PUT',body:body({desiredRoles:value(f,'desiredRoles').split(',').map(x=>x.trim()).filter(Boolean),location:value(f,'location')||null,commuteKm:n('commuteKm'),salaryMin:n('salaryMin'),salaryMode:value(f,'salaryMode')||'EXCLUDE_LOWER',remotePreferences:values(f,'remote'),contractPreferences:values(f,'contract'),shiftPreferences:{nights:f.has('allowNights'),weekends:f.has('allowWeekends')},availability:value(f,'availability')||null})});toast('Profil zapisany');await loadMe();});
$('#factForm').addEventListener('submit',async ev=>{ev.preventDefault();const form=ev.currentTarget as HTMLFormElement,f=new FormData(form);await api('/api/career-truth/facts',{method:'POST',body:body({type:value(f,'type'),value:value(f,'value'),level:value(f,'level')||null})});form.reset();await loadCareerTruth();toast('Fakt dodany');});
$('#experienceForm').addEventListener('submit',async ev=>{ev.preventDefault();const form=ev.currentTarget as HTMLFormElement,f=new FormData(form);await api('/api/experiences',{method:'POST',body:body({employer:value(f,'employer'),title:value(f,'title'),startDate:value(f,'startDate')||null,endDate:value(f,'endDate')||null,current:f.has('current'),description:value(f,'description')||null,achievements:[]})});form.reset();await loadCareerTruth();toast('Doświadczenie dodane');});
$('#cvUploadForm').addEventListener('submit',async ev=>{ev.preventDefault();const file=$<HTMLInputElement>('#cvFile').files?.[0];if(!file)return;const bytes=new Uint8Array(await file.arrayBuffer());let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));try{const d=await api<{inferredFacts:unknown[]}>('/api/cv/upload',{method:'POST',body:body({filename:file.name,mimeType:file.type||'text/plain',base64:btoa(bin)})});msg('#cvUploadMessage',`Wczytano. Fakty do sprawdzenia: ${d.inferredFacts.length}.`,true);await loadCareerTruth();}catch(e){msg('#cvUploadMessage',(e as Error).message);}});
$('#factsList').addEventListener('click',async ev=>{const target=ev.target as Element;const del=target.closest<HTMLButtonElement>('[data-delete-fact]');if(del){try{await api(`/api/career-truth/facts/${del.dataset.deleteFact}`,{method:'DELETE'});await loadCareerTruth();toast('Fakt usunięty');}catch(e){toast((e as Error).message);}return;}const b=target.closest<HTMLButtonElement>('[data-fact]');if(!b)return;try{await api(`/api/career-truth/facts/${b.dataset.fact}/status`,{method:'PATCH',body:body({status:b.dataset.status})});await loadCareerTruth();toast(b.dataset.status==='NOT_POSSESSED'?'Fakt oznaczony jako nieprawdziwy':'Fakt potwierdzony');}catch(e){toast((e as Error).message);}});
$('#experiencesList').addEventListener('click',async ev=>{const b=(ev.target as Element).closest<HTMLButtonElement>('[data-delete-experience]');if(!b)return;try{await api(`/api/experiences/${b.dataset.deleteExperience}`,{method:'DELETE'});await loadCareerTruth();toast('Doświadczenie usunięte');}catch(e){toast((e as Error).message);}});
$('#jobForm').addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget as HTMLFormElement);try{msg('#jobMessage','Analizuję…',true);const j=await api<{jobId:string}>('/api/jobs/parse',{method:'POST',body:body({text:value(f,'text')})});currentJob=j.jobId;const d=await api<{decisionId:string;decision:Json}>(`/api/jobs/${currentJob}/decide`,{method:'POST',body:'{}'});renderDecision(d);msg('#jobMessage','Analiza gotowa.',true);}catch(e){msg('#jobMessage',(e as Error).message);}});
$('#decisionArea').addEventListener('click',async ev=>{const t=ev.target as HTMLElement;if(t.id==='prepareButton'){const d=await api<{package:{message:string;fitSummary:string};pdfUrl:string}>(`/api/jobs/${currentJob}/application-package`,{method:'POST',body:'{}'});$('#packageArea').innerHTML=`<h3>Pakiet aplikacyjny</h3><p>${esc(d.package.fitSummary)}</p><pre class="package">${esc(d.package.message)}</pre><div class="fact-actions"><a class="button button-secondary" href="${esc(d.pdfUrl)}">Pobierz CV PDF</a><button id="markApplied" class="button button-primary">Oznacz jako wysłane</button></div>`;}const o=t.closest<HTMLButtonElement>('[data-override]');if(o&&currentDecision){await api(`/api/decisions/${currentDecision}/override`,{method:'POST',body:body({override:o.dataset.override,reason:null})});toast('Twoja decyzja została zapisana');}if(t.id==='markApplied'){await api('/api/applications',{method:'POST',body:body({jobId:currentJob,status:'APPLIED'})});toast('Aplikacja zapisana');showScreen('applications');}});
$('#applicationsList').addEventListener('change',async ev=>{const s=ev.target as HTMLSelectElement;if(s.dataset.appStatus){try{await api(`/api/applications/${s.dataset.appStatus}/status`,{method:'PATCH',body:body({status:s.value})});toast('Status zmieniony');}catch(e){toast((e as Error).message);await loadApplications();}}if(s.dataset.outcome&&s.value){await api(`/api/applications/${s.dataset.outcome}/outcomes`,{method:'POST',body:body({outcomeType:s.value})});toast('Wynik zapisany');s.value='';}});
$('#saveConsentButton').addEventListener('click',async()=>{const granted=$<HTMLInputElement>('#analyticsConsent').checked;try{await api('/api/consents/analytics',{method:'PUT',body:body({granted})});await loadConsents();toast('Zgoda została zapisana');}catch(e){toast((e as Error).message);}});
$('#exportButton').addEventListener('click',async()=>{const d=await api('/api/export');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download='job-data-export.json';a.click();URL.revokeObjectURL(a.href);});
$('#deleteAccountButton').addEventListener('click',async()=>{const confirmation=$<HTMLInputElement>('#deleteConfirmation').value;try{await api('/api/account',{method:'DELETE',body:body({confirmation})});setLoggedIn(false);location.hash='';toast('Konto usunięte');}catch(e){toast((e as Error).message);}});
$$('[data-wizard-tab]').forEach(tab=>tab.addEventListener('click',()=>{const s=Number(tab.getAttribute('data-wizard-tab'));if(s>=1&&s<=3)setWizardStep(s);}));
$('#wizardFormStep1').addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget as HTMLFormElement);const n=(k:string)=>value(f,k)?Number(value(f,k)):null;try{await api('/api/profile',{method:'PUT',body:body({desiredRoles:value(f,'wizardDesiredRoles').split(',').map(x=>x.trim()).filter(Boolean),location:value(f,'wizardLocation')||null,commuteKm:n('wizardCommuteKm'),salaryMin:n('wizardSalaryMin'),salaryMode:value(f,'wizardSalaryMode')||'EXCLUDE_LOWER',remotePreferences:me?.profile.remotePreferences??[],contractPreferences:me?.profile.contractPreferences??[],shiftPreferences:me?.profile.shiftPreferences??{nights:null,weekends:null},availability:me?.profile.availability??null})});msg('#wizardMsgStep1','Preferencje zapisane!',true);toast('Krok 1 zapisany');await loadMe();setWizardStep(2);}catch(e){msg('#wizardMsgStep1',(e as Error).message);}});
$('#wizardCvForm').addEventListener('submit',async ev=>{ev.preventDefault();const file=$<HTMLInputElement>('#wizardCvFile').files?.[0];if(!file)return;const bytes=new Uint8Array(await file.arrayBuffer());let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));try{msg('#wizardCvMsg','Przetwarzanie CV…',true);const d=await api<{inferredFacts:unknown[]}>('/api/cv/upload',{method:'POST',body:body({filename:file.name,mimeType:file.type||'text/plain',base64:btoa(bin)})});msg('#wizardCvMsg',`Wczytano CV! Fakty do sprawdzenia: ${d.inferredFacts.length}.`,true);toast('CV wczytane');await loadCareerTruth();}catch(e){msg('#wizardCvMsg',(e as Error).message);}});
$('#wizardFactForm').addEventListener('submit',async ev=>{ev.preventDefault();const form=ev.currentTarget as HTMLFormElement,f=new FormData(form);const v=value(f,'value');if(!v)return;try{await api('/api/career-truth/facts',{method:'POST',body:body({type:'SKILL',value:v,level:null})});form.reset();msg('#wizardFactMsg',`Dodano: ${v}`,true);toast('Umiejętność dodana');await loadCareerTruth();}catch(e){msg('#wizardFactMsg',(e as Error).message);}});
$('#wizardBackToStep1').addEventListener('click',()=>setWizardStep(1));
$('#wizardGoToStep3').addEventListener('click',()=>setWizardStep(3));
$('#wizardSkipStep2').addEventListener('click',()=>setWizardStep(3));
$('#wizardInsertSampleOffer').addEventListener('click',()=>{const sample='Stanowisko: Magazynier / Operator wózka widłowego\\nFirma: LogisTech Sp. z o.o.\\nLokalizacja: Gdynia\\nWynagrodzenie: 5500 - 6500 PLN brutto / mies.\\nWymagania:\\n- Uprawnienia UDT na wózki jezdniowe (warunek konieczny)\\n- Doświadczenie w pracy na magazynie min. 1 rok\\n- Dyspozycyjność do pracy zmianowej\\nOferujemy:\\n- Stabilne zatrudnienie w oparciu o Umowę o Pracę\\n- Premie miesięczne i pakiet benefitów\\n- Przyjazną atmosferę w zespole';$<HTMLTextAreaElement>('#wizardJobText').value=sample;});
$('#wizardBackToStep2').addEventListener('click',()=>setWizardStep(2));
$('#wizardJobForm').addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget as HTMLFormElement);try{msg('#wizardJobMsg','Analizuję ofertę…',true);const j=await api<{jobId:string}>('/api/jobs/parse',{method:'POST',body:body({text:value(f,'text')})});currentJob=j.jobId;const d=await api<{decisionId:string;decision:Json}>(`/api/jobs/${currentJob}/decide`,{method:'POST',body:'{}'});renderDecision(d);msg('#wizardJobMsg','Analiza gotowa! Przechodzę do werdyktu…',true);location.hash='job';showScreen('job');$('#decisionArea').scrollIntoView({behavior:'smooth'});}catch(e){msg('#wizardJobMsg',(e as Error).message);}});
([['wizardDesiredRoles','#wizardRolesChips'],['desiredRoles','#profileRolesChips']] as const).forEach(([name,containerId])=>{document.addEventListener('input',ev=>{const target=ev.target as HTMLInputElement;if(target&&target.name===name)syncRolesChips(name,containerId);});$(containerId)?.addEventListener('click',ev=>{const btn=(ev.target as HTMLElement).closest<HTMLButtonElement>('.role-chip-remove');if(!btn)return;const input=$(`input[name="${name}"]`) as HTMLInputElement|null;if(!input)return;const idx=Number(btn.dataset.roleIndex);const roles=input.value.split(',').map(s=>s.trim()).filter(Boolean);if(idx>=0&&idx<roles.length){roles.splice(idx,1);input.value=roles.join(', ');syncRolesChips(name,containerId);input.dispatchEvent(new Event('input',{bubbles:true}));}});});
window.addEventListener('hashchange',()=>{if(me)showScreen(location.hash.slice(1)||'start');});if('serviceWorker'in navigator)void navigator.serviceWorker.register('/sw.js');void loadMe();