export {};
type Path={sourceRole:string;targetRole:string;savedJobs:number;localMentions:number;localSourceCount:number;salaryMin:number|null;salaryMax:number|null;transferableSkills:string[];missingSkills:string[];confirmedSkillCount:number;targetRequirementCount:number;suggestedLearning:string[];confidence:string;difficulty:string;evidence:string[];uncertainty:string[]};type Report={sourceRole:string;paths:Path[];message:string};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));async function api<T>(p:string,i:RequestInit={}):Promise<T>{const r=await fetch(p,{...i,headers:{...(i.body?{'content-type':'application/json'}:{}),...(i.headers??{})}});const d=await r.json().catch(()=>({})) as T&{error?:{message?:string}};if(!r.ok)throw new Error(d.error?.message??`HTTP ${r.status}`);return d;}const list=(x:string[])=>x.length?`<ul>${x.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:'<p class="hint">Brak potwierdzonych danych.</p>';
function ensure(){let s=document.querySelector<HTMLElement>('[data-screen="career-transition"]');if(s)return s;const mobile=document.querySelector('.mobile-nav'),side=document.querySelector('.sidebar'),content=document.querySelector('.content');if(!mobile||!side||!content)throw new Error('Brak kontenera aplikacji.');const m=document.createElement('button');m.type='button';m.className='nav-item';m.dataset.view='career-transition';m.textContent='Ścieżki';mobile.append(m);const b=document.createElement('button');b.type='button';b.className='side-link';b.dataset.view='career-transition';b.textContent='Zmiana kariery';side.append(b);s=document.createElement('section');s.className='screen hidden';s.dataset.screen='career-transition';s.innerHTML=`<div class="screen-heading"><p class="eyebrow">Career Transition V2</p><h2>Sąsiednie ścieżki kariery</h2><p>Kuratorowany graf ról jest tylko punktem startu. Każdą ścieżkę porównujemy z Twoimi potwierdzonymi kompetencjami, zapisanymi ofertami i dostępnymi danymi lokalnymi.</p></div><div id="transitionMessage" class="message" aria-live="polite"></div><div id="transitionResult" class="stack"></div>`;content.append(s);for(const x of[m,b])x.addEventListener('click',()=>{location.hash='career-transition';show();void load();});return s;}
function show(){document.querySelectorAll<HTMLElement>('[data-screen]').forEach(e=>e.classList.toggle('hidden',e.dataset.screen!=='career-transition'));document.querySelectorAll<HTMLElement>('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view==='career-transition'));}
function render(r:Report){const root=document.querySelector<HTMLElement>('#transitionResult');if(!root)return;root.innerHTML=`<div class="card"><h3>Start: ${esc(r.sourceRole||'nieustalony')}</h3><p>${esc(r.message)}</p></div>${r.paths.map(p=>`<article class="card"><div class="row-between"><h3>${esc(p.targetRole)}</h3><div><span class="badge">${esc(p.difficulty)}</span> <span class="badge">${esc(p.confidence.replaceAll('_',' '))}</span></div></div><p>${p.savedJobs} zapisanych ofert · ${p.localMentions} lokalnych snapshotów</p>${p.salaryMin===null&&p.salaryMax===null?'':`<p>Obserwowane widełki: <strong>${p.salaryMin??'—'}–${p.salaryMax??'—'} zł</strong></p>`}<h4>Kompetencje przenoszalne — potwierdzone</h4>${list(p.transferableSkills)}<h4>Niepotwierdzone wymagania</h4>${list(p.missingSkills)}<h4>Sugerowana nauka</h4>${list(p.suggestedLearning)}<h4>Dowody</h4>${list(p.evidence)}<h4>Niepewność</h4>${list(p.uncertainty)}<button class="button button-secondary" type="button" data-explore="${esc(p.targetRole)}">Zapisz jako rozważaną ścieżkę</button></article>`).join('')}`;root.querySelectorAll<HTMLButtonElement>('[data-explore]').forEach(btn=>btn.addEventListener('click',()=>void explore(btn.dataset.explore??'')));}
function msg(t:string,e=false){const x=document.querySelector<HTMLElement>('#transitionMessage');if(x){x.textContent=t;x.className=`message ${e?'error':'success'}`;}}
async function load(){try{const d=await api<{report:Report}>('/api/career-transition');render(d.report);msg('Ścieżki obliczone na aktualnych danych.');}catch(e){msg((e as Error).message,true);}}
async function explore(targetRole:string){try{await api('/api/career-transition/explorations',{method:'POST',body:JSON.stringify({targetRole})});msg(`Zapisano ścieżkę: ${targetRole}.`);}catch(e){msg((e as Error).message,true);}}
let enabled=false;async function refresh(){try{const d=await api<{features:{career_transition?:boolean}}>('/api/features');enabled=d.features.career_transition===true;if(enabled){ensure();if(location.hash==='#career-transition'){show();await load();}}}catch{enabled=false;}}window.addEventListener('hashchange',()=>{if(enabled&&location.hash==='#career-transition'){show();void load();}});const app=document.querySelector('#appView');if(app)new MutationObserver(()=>{if(!app.classList.contains('hidden'))void refresh();}).observe(app,{attributes:true,attributeFilter:['class']});void refresh();
