export {};
type Target={kind:'INTERVIEW'|'MISSING_SKILL'|'CERTIFICATION'|'JOB_REQUIREMENT';key:string;label:string;context:string;evidence:string[];unknowns:string[]};type Plan={target:Target;budgetMinutes:number;tasks:Array<{minutes:number;title:string;instruction:string}>;boundaries:string[]};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
async function api<T>(p:string,i:RequestInit={}):Promise<T>{const r=await fetch(p,{...i,headers:{...(i.body?{'content-type':'application/json'}:{}),...(i.headers??{})}});const d=await r.json().catch(()=>({})) as T&{error?:{message?:string}};if(!r.ok)throw new Error(d.error?.message??`HTTP ${r.status}`);return d;}
function ensure(){let s=document.querySelector<HTMLElement>('[data-screen="learning"]');if(s)return s;const mobile=document.querySelector('.mobile-nav'),side=document.querySelector('.sidebar'),content=document.querySelector('.content');if(!mobile||!side||!content)throw new Error('Brak kontenera aplikacji.');const m=document.createElement('button');m.type='button';m.className='nav-item';m.dataset.view='learning';m.textContent='Nauka';mobile.append(m);const b=document.createElement('button');b.type='button';b.className='side-link';b.dataset.view='learning';b.textContent='Szybka nauka';side.append(b);s=document.createElement('section');s.className='screen hidden';s.dataset.screen='learning';s.innerHTML=`<div class="screen-heading"><p class="eyebrow">Just-in-Time Learning V1.5</p><h2>Szybka nauka pod konkretny cel</h2><p>Nie budujemy kursu. Wybierz realny cel z Twoich ofert lub aplikacji i czas, który masz teraz.</p></div><div class="card"><label>Cel<select id="learningTarget"></select></label><label>Budżet czasu<select id="learningBudget"><option value="15">15 minut</option><option value="30">30 minut</option><option value="60">60 minut</option><option value="120">2 godziny</option></select></label><button id="learningBuild" class="button" type="button">Ułóż plan</button><div id="learningMessage" class="message" aria-live="polite"></div></div><div id="learningPlan" class="stack section-gap" aria-live="polite"></div>`;content.append(s);for(const x of[m,b])x.addEventListener('click',()=>{location.hash='learning';show();void load();});s.querySelector('#learningBuild')?.addEventListener('click',()=>void build());return s;}
function show(){document.querySelectorAll<HTMLElement>('[data-screen]').forEach(e=>e.classList.toggle('hidden',e.dataset.screen!=='learning'));document.querySelectorAll<HTMLElement>('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view==='learning'));}
let targets:Target[]=[];function renderTargets(){const sel=document.querySelector<HTMLSelectElement>('#learningTarget');if(!sel)return;sel.innerHTML=targets.length?targets.map((t,i)=>`<option value="${i}">${esc(t.label)} · ${esc(t.kind)}</option>`).join(''):'<option value="">Brak realnych celów</option>';}
function renderPlan(p:Plan){const root=document.querySelector<HTMLElement>('#learningPlan');if(!root)return;root.innerHTML=`<article class="card"><span class="badge">${p.budgetMinutes} min</span><h3>${esc(p.target.label)}</h3><p>${esc(p.target.context)}</p><h4>Dlaczego ten cel istnieje</h4><ul>${p.target.evidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>${p.tasks.map(t=>`<article class="card"><div class="row-between"><h3>${esc(t.title)}</h3><span class="badge">${t.minutes} min</span></div><p>${esc(t.instruction)}</p></article>`).join('')}<article class="card"><h3>Granice</h3><ul>${p.boundaries.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`;}
function msg(t:string,e=false){const x=document.querySelector<HTMLElement>('#learningMessage');if(x){x.textContent=t;x.className=`message ${e?'error':'success'}`;}}
async function load(){try{const d=await api<{targets:Target[]}>('/api/learning/targets');targets=d.targets;renderTargets();msg(targets.length?'Cele gotowe.':'Dodaj oferty lub aplikację na rozmowie, aby utworzyć cel.');}catch(e){msg((e as Error).message,true);}}
async function build(){const idx=Number(document.querySelector<HTMLSelectElement>('#learningTarget')?.value??'-1'),target=targets[idx],budget=Number(document.querySelector<HTMLSelectElement>('#learningBudget')?.value??15);if(!target){msg('Brak wybranego celu.',true);return;}try{const d=await api<{plan:Plan}>('/api/learning/plan',{method:'POST',body:JSON.stringify({targetKind:target.kind,targetKey:target.key,budgetMinutes:budget})});renderPlan(d.plan);msg('Plan utworzony dla realnego celu.');}catch(e){msg((e as Error).message,true);}}
let enabled=false;async function refresh(){try{const d=await api<{features:{just_in_time_learning?:boolean}}>('/api/features');enabled=d.features.just_in_time_learning===true;if(enabled){ensure();if(location.hash==='#learning'){show();await load();}}}catch{enabled=false;}}
window.addEventListener('hashchange',()=>{if(enabled&&location.hash==='#learning'){show();void load();}});const app=document.querySelector('#appView');if(app)new MutationObserver(()=>{if(!app.classList.contains('hidden'))void refresh();}).observe(app,{attributes:true,attributeFilter:['class']});void refresh();
