export {};
type AppItem={id:string;status:string;title:string|null;company:string|null};
type Suggestion={id:string;applicationId:string;suggestionType:string;suggestedStatus:string;confidence:number;evidenceCodes:string[];sourceKind:string;sourceLabel:string|null;confirmedAt:string|null;dismissedAt:string|null;createdAt:string;jobTitle:string|null;company:string|null;currentStatus:string|null};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
async function api<T>(path:string,init:RequestInit={}):Promise<T>{const response=await fetch(path,{...init,headers:{...(init.body?{'content-type':'application/json'}:{}),...(init.headers??{})}});const data=await response.json().catch(()=>({})) as T&{error?:{message?:string}};if(!response.ok)throw new Error(data.error?.message??`HTTP ${response.status}`);return data;}
const labels:Record<string,string>={REJECTED:'Prawdopodobne odrzucenie',INTERVIEW:'Prawdopodobne zaproszenie na rozmowę',OFFER:'Prawdopodobna oferta',RECRUITER_CONTACT:'Prawdopodobny kontakt rekrutera'};
const evidenceLabel:Record<string,string>={REJECTION_LANGUAGE:'Wiadomość zawiera typowe sformułowania odmowy.',INTERVIEW_INVITATION:'Wiadomość zawiera typowe sformułowania zaproszenia na rozmowę.',OFFER_LANGUAGE:'Wiadomość zawiera typowe sformułowania oferty zatrudnienia.',RECRUITER_CONTACT:'Wiadomość zawiera typowe sformułowania kontaktu rekrutera.'};
function ensure():HTMLElement{let screen=document.querySelector<HTMLElement>('[data-screen="outcome-inbox"]');if(screen)return screen;const mobile=document.querySelector('.mobile-nav'),side=document.querySelector('.sidebar'),content=document.querySelector('.content');if(!mobile||!side||!content)throw new Error('Brak kontenera aplikacji.');const m=document.createElement('button');m.type='button';m.className='nav-item';m.dataset.view='outcome-inbox';m.textContent='Wyniki';mobile.append(m);const d=document.createElement('button');d.type='button';d.className='side-link';d.dataset.view='outcome-inbox';d.textContent='Outcome Inbox';side.append(d);screen=document.createElement('section');screen.className='screen hidden';screen.dataset.screen='outcome-inbox';screen.innerHTML=`<div class="screen-heading"><p class="eyebrow">Outcome Inbox V2</p><h2>Co oznacza wiadomość od firmy?</h2><p>Wklej wiadomość rekrutacyjną i wybierz aplikację. Analiza jest sugestią — <strong>status nigdy nie zmienia się bez Twojego potwierdzenia</strong>. Surowa treść wiadomości nie jest zapisywana.</p></div><div id="outcomeInboxMessage" class="message" aria-live="polite"></div><form id="outcomeInboxForm" class="card stack"><label>Aplikacja<select name="applicationId" required><option value="">Wybierz aplikację</option></select></label><label>Opcjonalna etykieta źródła<input name="sourceLabel" maxlength="200" placeholder="np. e-mail od rekrutera"></label><label>Treść wiadomości<textarea name="messageText" required minlength="12" maxlength="20000" rows="7" placeholder="Wklej wiadomość rekrutacyjną"></textarea></label><button class="button" type="submit">Przeanalizuj wiadomość</button><p class="hint">Po analizie zapisujemy jedynie skrót kryptograficzny, typ sygnału i ogólne kody dowodów — nie treść wiadomości.</p></form><div id="outcomeInboxSuggestions" class="stack"></div>`;content.append(screen);for(const button of[m,d])button.addEventListener('click',()=>{location.hash='outcome-inbox';show();void load();});screen.querySelector<HTMLFormElement>('#outcomeInboxForm')?.addEventListener('submit',event=>void analyze(event));screen.querySelector('#outcomeInboxSuggestions')?.addEventListener('click',event=>void action(event));return screen;}
function show(){document.querySelectorAll<HTMLElement>('[data-screen]').forEach(e=>e.classList.toggle('hidden',e.dataset.screen!=='outcome-inbox'));document.querySelectorAll<HTMLElement>('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view==='outcome-inbox'));}
function message(text:string,error=false){const node=document.querySelector<HTMLElement>('#outcomeInboxMessage');if(node){node.textContent=text;node.className=`message ${error?'error':'success'}`;}}
function render(items:Suggestion[]){const root=document.querySelector<HTMLElement>('#outcomeInboxSuggestions');if(!root)return;root.innerHTML=items.length?items.map(item=>`<article class="card"><div class="row-between"><div><p class="eyebrow">${esc(item.company??'Firma')} · ${esc(item.jobTitle??'Aplikacja')}</p><h3>${esc(labels[item.suggestionType]??item.suggestionType)}</h3></div><span class="badge">${Math.round(item.confidence*100)}% pewności</span></div><p>Status: <strong>${esc(item.currentStatus??'—')}</strong> → sugerowany: <strong>${esc(item.suggestedStatus)}</strong></p><ul>${item.evidenceCodes.map(code=>`<li>${esc(evidenceLabel[code]??code)}</li>`).join('')}</ul>${item.confirmedAt?'<p class="message success">Potwierdzono przez użytkownika.</p>':item.dismissedAt?'<p class="hint">Sugestia odrzucona przez użytkownika.</p>':`<div class="fact-actions"><button type="button" class="mini-button good" data-confirm="${esc(item.id)}">Potwierdź i zaktualizuj status</button><button type="button" class="mini-button bad" data-dismiss="${esc(item.id)}">To nie ten wynik</button></div>`}</article>`).join(''):'<div class="card"><p class="hint">Brak sugestii. Wklejenie wiadomości bez jednoznacznego sygnału nie zmieni statusu.</p></div>';}
async function load(){try{const [apps,inbox]=await Promise.all([api<{applications:AppItem[]}>('/api/applications'),api<{suggestions:Suggestion[]}>('/api/outcome-inbox')]);const select=document.querySelector<HTMLSelectElement>('#outcomeInboxForm select[name="applicationId"]');if(select){select.innerHTML='<option value="">Wybierz aplikację</option>'+apps.applications.map(a=>`<option value="${esc(a.id)}">${esc(a.company??'Firma')} — ${esc(a.title??'Oferta')} (${esc(a.status)})</option>`).join('');}render(inbox.suggestions);}catch(error){message((error as Error).message,true);}}
async function analyze(event:Event){event.preventDefault();const form=event.currentTarget as HTMLFormElement,data=new FormData(form);try{const response=await api<{suggestion:Suggestion|null;message:string}>('/api/outcome-inbox/analyze',{method:'POST',body:JSON.stringify({applicationId:String(data.get('applicationId')??''),sourceLabel:String(data.get('sourceLabel')??'').trim()||null,messageText:String(data.get('messageText')??'')})});message(response.message,response.suggestion===null);if(response.suggestion){form.querySelector<HTMLTextAreaElement>('textarea[name="messageText"]')!.value='';await load();}}catch(error){message((error as Error).message,true);}}
async function action(event:Event){const target=event.target as Element;const confirm=target.closest<HTMLButtonElement>('[data-confirm]'),dismiss=target.closest<HTMLButtonElement>('[data-dismiss]');if(!confirm&&!dismiss)return;try{if(confirm){await api(`/api/outcome-inbox/${confirm.dataset.confirm}/confirm`,{method:'PATCH'});message('Status zaktualizowano dopiero po Twoim potwierdzeniu.');}else if(dismiss){await api(`/api/outcome-inbox/${dismiss.dataset.dismiss}/dismiss`,{method:'PATCH'});message('Sugestię oznaczono jako nietrafioną.');}await load();}catch(error){message((error as Error).message,true);}}
let enabled=false;async function refresh(){try{const data=await api<{features:{outcome_inbox?:boolean}}>('/api/features');enabled=data.features.outcome_inbox===true;if(enabled){ensure();if(location.hash==='#outcome-inbox'){show();await load();}}}catch{enabled=false;}}window.addEventListener('hashchange',()=>{if(enabled&&location.hash==='#outcome-inbox'){show();void load();}});const app=document.querySelector('#appView');if(app)new MutationObserver(()=>{if(!app.classList.contains('hidden'))void refresh();}).observe(app,{attributes:true,attributeFilter:['class']});void refresh();
