export {};
type Confidence='ZA_MALO_DANYCH'|'WCZESNY_SYGNAL'|'PRAWDOPODOBNY_WNIOSEK'|'SILNY_WNIOSEK';
type Assumption={skill:string;normalizedSkill:string;estimatedCost:number|null;estimatedHours:number|null;certificationRequired:boolean|null;certificationNote:string|null};
type Candidate={skill:string;normalizedSkill:string;ontologyType:string;requirementCount:number;mustHaveCount:number;savedJobSample:number;potentiallyUnlockedJobs:number;localMentions:number;localSourceCount:number;salaryDifference:number|null;salarySample:number;possession:string;assumption:Assumption|null;confidence:Confidence;opportunityScore:number;evidence:string[];uncertainty:string[];nextStep:string};
type Report={candidates:Candidate[];savedJobSample:number;confidence:Confidence;message:string};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
async function api<T>(path:string,init:RequestInit={}):Promise<T>{const r=await fetch(path,{...init,headers:{...(init.body?{'content-type':'application/json'}:{}),...(init.headers??{})}});const d=await r.json().catch(()=>({})) as T&{error?:{message?:string}};if(!r.ok)throw new Error(d.error?.message??`HTTP ${r.status}`);return d;}
const labels:Record<Confidence,string>={ZA_MALO_DANYCH:'ZA MAŁO DANYCH',WCZESNY_SYGNAL:'WCZESNY SYGNAŁ',PRAWDOPODOBNY_WNIOSEK:'PRAWDOPODOBNY WNIOSEK',SILNY_WNIOSEK:'SILNY WNIOSEK'};
function list(items:string[]){return `<ul>${items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`;}
function ensureUi(){let s=document.querySelector<HTMLElement>('[data-screen="skill-roi"]');if(s)return s;const mobile=document.querySelector('.mobile-nav'),side=document.querySelector('.sidebar'),content=document.querySelector('.content');if(!mobile||!side||!content)throw new Error('Brak kontenera aplikacji.');const m=document.createElement('button');m.type='button';m.className='nav-item';m.dataset.view='skill-roi';m.textContent='Rozwój';mobile.append(m);const b=document.createElement('button');b.type='button';b.className='side-link';b.dataset.view='skill-roi';b.textContent='Skill ROI';side.append(b);s=document.createElement('section');s.className='screen hidden';s.dataset.screen='skill-roi';s.innerHTML=`<div class="screen-heading"><p class="eyebrow">V1.5 · decyzja oparta na zapisanej próbce</p><h2>Czego najbardziej opłaca Ci się teraz nauczyć?</h2><p>Porównujemy wymagania Twoich zapisanych ofert, potwierdzone Career Truth, lokalne dane i Twoje własne założenia kosztu/czasu. Nie obiecujemy pracy ani finansowego zwrotu.</p></div><div id="skillRoiMessage" class="message" aria-live="polite"></div><div id="skillRoiResult" class="stack"></div>`;content.append(s);for(const x of[m,b])x.addEventListener('click',()=>{location.hash='skill-roi';show();void load();});return s;}
function show(){document.querySelectorAll<HTMLElement>('[data-screen]').forEach(e=>e.classList.toggle('hidden',e.dataset.screen!=='skill-roi'));document.querySelectorAll<HTMLElement>('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view==='skill-roi'));}
function render(r:Report){const root=document.querySelector<HTMLElement>('#skillRoiResult');if(!root)return;root.innerHTML=`<div class="card"><div class="row-between"><strong>Pewność całej próbki</strong><span class="badge">${esc(labels[r.confidence])}</span></div><p>${esc(r.message)}</p></div>${r.candidates.map((c,i)=>`<article class="card" data-skill="${esc(c.normalizedSkill)}"><div class="row-between"><div><span class="badge">#${i+1}</span> <span class="badge">${esc(c.ontologyType)}</span></div><strong>${esc(labels[c.confidence])}</strong></div><h3>${esc(c.skill)}</h3><p><strong>${c.potentiallyUnlockedJobs}</strong> potencjalnie odblokowanych ofert w zapisanej próbce · ${c.mustHaveCount} MUST_HAVE · ${c.requirementCount} ofert z wymaganiem</p>${c.salaryDifference===null?'':`<p>Porównywalna różnica płac: <strong>${Math.round(c.salaryDifference)} zł/mies.</strong> <span class="hint">(próbka ${c.salarySample})</span></p>`}<h4>Dowody</h4>${list(c.evidence)}<h4>Niepewność</h4>${list(c.uncertainty)}<p><strong>Następny krok:</strong> ${esc(c.nextStep)}</p><form class="stack skill-assumption" data-key="${esc(c.normalizedSkill)}" data-label="${esc(c.skill)}"><label>Twój koszt zdobycia (zł)<input name="cost" type="number" min="0" max="1000000" step="1" value="${c.assumption?.estimatedCost??''}"></label><label>Twój czas (godz.)<input name="hours" type="number" min="0" max="5000" step="0.5" value="${c.assumption?.estimatedHours??''}"></label><label>Czy formalna certyfikacja jest wymagana według zweryfikowanej przez Ciebie informacji?<select name="cert"><option value="" ${c.assumption?.certificationRequired==null?'selected':''}>Nie wiem</option><option value="yes" ${c.assumption?.certificationRequired===true?'selected':''}>Tak</option><option value="no" ${c.assumption?.certificationRequired===false?'selected':''}>Nie</option></select></label><label>Notatka / źródło weryfikacji<input name="note" maxlength="500" value="${esc(c.assumption?.certificationNote??'')}"></label><button class="button button-secondary" type="submit">Zapisz założenia</button></form></article>`).join('')}`;root.querySelectorAll<HTMLFormElement>('.skill-assumption').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();void save(f);}));}
async function save(form:HTMLFormElement){const key=form.dataset.key??'',skill=form.dataset.label??key,fd=new FormData(form);const n=(name:string)=>{const x=String(fd.get(name)??'').trim();return x===''?null:Number(x)};const cert=String(fd.get('cert')??'');try{const data=await api<{report:Report}>(`/api/skill-roi/assumptions/${encodeURIComponent(key)}`,{method:'PUT',body:JSON.stringify({skill,estimatedCost:n('cost'),estimatedHours:n('hours'),certificationRequired:cert===''?null:cert==='yes',certificationNote:String(fd.get('note')??'').trim()||null})});render(data.report);msg('Założenia zapisane.');}catch(e){msg((e as Error).message,true);}}
function msg(text:string,error=false){const el=document.querySelector<HTMLElement>('#skillRoiMessage');if(el){el.textContent=text;el.className=`message ${error?'error':'success'}`;}}
async function load(){try{const d=await api<{report:Report}>('/api/skill-roi');render(d.report);msg('Ranking przeliczony na podstawie aktualnych zapisanych danych.');}catch(e){msg((e as Error).message,true);}}
let enabled=false;async function refresh(){try{const d=await api<{features:{skill_roi?:boolean}}>('/api/features');enabled=d.features.skill_roi===true;if(enabled){ensureUi();if(location.hash==='#skill-roi'){show();await load();}}}catch{enabled=false;}}
window.addEventListener('hashchange',()=>{if(enabled&&location.hash==='#skill-roi'){show();void load();}});const app=document.querySelector('#appView');if(app)new MutationObserver(()=>{if(!app.classList.contains('hidden'))void refresh();}).observe(app,{attributes:true,attributeFilter:['class']});void refresh();
